-- Add soft delete fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_alias VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deletion_date TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
